### ISSUE TITLE
HOW TO SOLVE

### ISSUE THREAD

**Issue by tharini1517** [ravinduu/RFID-Based-Attendance-System-using-Arduino#2]
sketch_jun07a:18:44: error: 'POSITIVE' was not declared in this scope
 LiquidCrystal_I2C lcd(0x27,2,1,0,4,5,6,7,3,POSITIVE);//instance for lcd display
                                            ^~~~~~~~
exit status 1
'POSITIVE' was not declared in this scope

**Comment by kanissh** [comment]
@ravinduu

**Comment by ravinduu** [comment]
@tharini1517 Have you tried using "LiquidCrystal" instead of "LiquidCrystal_I2C"? Check in your libraries for the I2C LiquidCrystal folder and check the spelling of the folder name.
